// ClipboardModel.swift - the clipboard history engine. Polls NSPasteboard's
// changeCount twice a second (the only way macOS offers, same as every
// clipboard manager). Captures text, images, and copied files. Skips anything
// a password manager marks concealed or transient. History persists as JSON
// in Application Support; images are stored as PNG files next to it.

import AppKit
import Combine

enum ClipKind: String, Codable {
    case text, image, file
}

struct ClipItem: Identifiable, Codable, Equatable {
    let id: UUID
    let kind: ClipKind
    var text: String          // text content, or file names for display
    var files: [String]       // file kind: full paths
    var imageFile: String?    // image kind: PNG filename inside images/
    var date: Date
    var pinned: Bool
    var app: String?          // app that was frontmost when copied

    var preview: String {
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        return t.count > 200 ? String(t.prefix(200)) + "…" : t
    }
}

final class ClipboardModel: ObservableObject {
    static let shared = ClipboardModel()

    @Published var items: [ClipItem] = []
    @Published var search = ""

    private let pb = NSPasteboard.general
    private var lastChange: Int
    private var timer: Timer?
    private let historyFile = supportDir().appendingPathComponent("history.json")
    private let imagesDir = supportDir().appendingPathComponent("images")

    // pasteboard types password managers use to say "do not record this"
    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private init() {
        lastChange = pb.changeCount
        try? FileManager.default.createDirectory(
            at: imagesDir, withIntermediateDirectories: true)
        load()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
        timer.map { RunLoop.main.add($0, forMode: .common) }
    }

    var filtered: [ClipItem] {
        guard !search.isEmpty else { return items }
        let q = search.lowercased()
        return items.filter {
            $0.text.lowercased().contains(q)
                || ($0.app ?? "").lowercased().contains(q)
        }
    }

    var pinnedItems: [ClipItem] { filtered.filter(\.pinned) }
    var unpinnedItems: [ClipItem] { filtered.filter { !$0.pinned } }

    // MARK: - Capture

    private func poll() {
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount

        let types = pb.types ?? []
        if Self.skipTypes.contains(where: types.contains) { return }

        let app = NSWorkspace.shared.frontmostApplication?.localizedName

        // copied files take priority (Finder puts both URLs and an icon image on the board)
        if let urls = pb.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let names = urls.map(\.lastPathComponent).joined(separator: ", ")
            add(ClipItem(id: UUID(), kind: .file, text: names,
                         files: urls.map(\.path), imageFile: nil,
                         date: Date(), pinned: false, app: app))
            return
        }

        if SettingsModel.shared.captureImages,
           let data = pb.data(forType: .png) ?? tiffAsPNG() {
            let name = UUID().uuidString + ".png"
            try? data.write(to: imagesDir.appendingPathComponent(name))
            add(ClipItem(id: UUID(), kind: .image, text: "Image",
                         files: [], imageFile: name,
                         date: Date(), pinned: false, app: app))
            return
        }

        if let s = pb.string(forType: .string),
           !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // same text copied again anywhere in history: float it to the top
            if let i = items.firstIndex(where: { $0.kind == .text && $0.text == s }) {
                var item = items.remove(at: i)
                item.date = Date()
                items.insert(item, at: 0)
                save()
                return
            }
            add(ClipItem(id: UUID(), kind: .text, text: s,
                         files: [], imageFile: nil,
                         date: Date(), pinned: false, app: app))
        }
    }

    private func tiffAsPNG() -> Data? {
        guard let tiff = pb.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func add(_ item: ClipItem) {
        items.insert(item, at: 0)
        trim()
        save()
    }

    private func trim() {
        let limit = SettingsModel.shared.historyLimit
        var unpinned = 0
        var keep: [ClipItem] = []
        var dropped: [ClipItem] = []
        for item in items {
            if item.pinned {
                keep.append(item)
            } else if unpinned < limit {
                unpinned += 1
                keep.append(item)
            } else {
                dropped.append(item)
            }
        }
        items = keep
        for item in dropped { removeImageFile(item) }
    }

    private func removeImageFile(_ item: ClipItem) {
        if let f = item.imageFile {
            try? FileManager.default.removeItem(at: imagesDir.appendingPathComponent(f))
        }
    }

    // MARK: - Actions

    func image(for item: ClipItem) -> NSImage? {
        guard let f = item.imageFile else { return nil }
        return NSImage(contentsOf: imagesDir.appendingPathComponent(f))
    }

    /// Put an item back on the pasteboard (its original form).
    func copy(_ item: ClipItem) {
        pb.clearContents()
        switch item.kind {
        case .text:
            pb.setString(item.text, forType: .string)
        case .image:
            if let f = item.imageFile,
               let data = try? Data(contentsOf: imagesDir.appendingPathComponent(f)) {
                pb.setData(data, forType: .png)
            }
        case .file:
            let urls = item.files.map { URL(fileURLWithPath: $0) as NSURL }
            pb.writeObjects(urls)
        }
        lastChange = pb.changeCount   // don't re-capture our own write
    }

    /// Copy stripping all formatting (text items only; others fall back to copy).
    func copyPlain(_ item: ClipItem) {
        guard item.kind == .text else { return copy(item) }
        pb.clearContents()
        pb.setString(item.text, forType: .string)
        lastChange = pb.changeCount
    }

    /// Copy, then paste into the frontmost app by synthesizing Cmd+V.
    /// Needs Accessibility; without it this is just a copy.
    func copyAndPaste(_ item: ClipItem) {
        copy(item)
        guard AXIsProcessTrusted() else { return }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) {
            let src = CGEventSource(stateID: .combinedSessionState)
            let down = CGEvent(keyboardEventSource: src, virtualKey: 9, keyDown: true)  // V
            let up = CGEvent(keyboardEventSource: src, virtualKey: 9, keyDown: false)
            down?.flags = .maskCommand
            up?.flags = .maskCommand
            down?.setIntegerValueField(.eventSourceUserData, value: expanderEventTag)
            up?.setIntegerValueField(.eventSourceUserData, value: expanderEventTag)
            down?.post(tap: .cghidEventTap)
            up?.post(tap: .cghidEventTap)
        }
    }

    func togglePin(_ item: ClipItem) {
        guard let i = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[i].pinned.toggle()
        save()
    }

    func delete(_ item: ClipItem) {
        removeImageFile(item)
        items.removeAll { $0.id == item.id }
        save()
    }

    /// Clears unpinned history. Pinned items stay.
    func clearUnpinned() {
        for item in items where !item.pinned { removeImageFile(item) }
        items.removeAll { !$0.pinned }
        save()
    }

    // MARK: - Persistence

    private func save() {
        if let data = try? JSONEncoder().encode(items) {
            try? data.write(to: historyFile)
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: historyFile),
              let saved = try? JSONDecoder().decode([ClipItem].self, from: data)
        else { return }
        items = saved
    }
}
